add order manager
MariaSneg/travelline pull request #3
Opened 2024-07-04 18:22 UTC by MariaSneg

2024-07-07 16:21 UTC, VladTL requested changes

2024-07-07 16:21 UTC, VladDotMe commented on OrderManager/editorconfig
> +root = true
editorconfig не применяется, должен называться с точки.
".editorconfig"

2024-07-07 16:21 UTC, VladDotMe commented on OrderManager/OrderManager/Program.cs
> +class OrderManager
Круто, что вынесла логику в класс. Но если делаешь класс - то надо выносить в отдельный файл.

2024-07-07 16:21 UTC, VladDotMe commented on OrderManager/editorconfig
> +root = true
А еще лучше положить его в корневую директорию репозитория чтобы он во всех проектах применялся.

2024-07-07 16:21 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +class Order
В отдельный файл

2024-07-07 16:21 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +    public string ProductName
Это и все проперти ниже можно сделать как AutoProperty

2024-07-07 16:21 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +        return ( answer == "Да" );
было бы неплохо обрабатывать "да" тоже

2024-07-07 16:21 UTC, VladTL commented on OrderManager/OrderManager/Program.cs
> +    public bool CheckOrder()
Между функциями оставляем новую строку

2024-07-08 08:24 UTC, MariaSneg commented
Вынесла классы в отдельные файлы, в Order сделала AutoProperty, подтверждение сделала регистронезависимым, .editconfig вынесла

2024-07-10 14:40 UTC, VladTL reviewed
Всякие мелочи, поправишь и можешь сливать

2024-07-10 14:40 UTC, VladDotMe commented on OrderManager/OrderManager/Order.cs
> +﻿class Order
не хватает неймспейса и модификатора доступа для класса

2024-07-10 14:40 UTC, VladDotMe commented on OrderManager/OrderManager/OrderManager.cs
> +﻿class OrderManager
не хватает неймспейса и модификатора доступа для класса

2024-07-10 14:40 UTC, VladTL commented on OrderManager/OrderManager/OrderManager.cs
> +    private Order _order = new Order();
а _order можно readonly сделать

2024-07-11 08:47 UTC, merged